/* Generated by Nim Compiler v0.17.2 */
/*   (c) 2017 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Linux, amd64, gcc */
/* Command for C compiler:
   gcc -c  -w  -I/home/ryan/dev/nim-0.17.2/lib -o /home/ryan/dev/nimmarkovchain/nimcache/NiMMarkov_nimmarkov.o /home/ryan/dev/nimmarkovchain/nimcache/NiMMarkov_nimmarkov.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg {
  RootObj Sup;
NI colonstate_;
FILE* fd1;
NimStringDesc* line2;
FILE* colontmp3_;
NimStringDesc* res4;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI lastSize;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* freeChunksList;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
};
typedef struct {
N_NIMCALL_PTR(NimStringDesc*, ClP_0) (NimStringDesc* filename, void* ClE_0);
void* ClE_0;
} tyProc_BLbewmRpDWz0SDsl9a9ci4xw;
typedef N_CLOSURE_PTR(NimStringDesc*, TM_obis3mXdRVckmiGcrQBusA_4) (NimStringDesc* filename);
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
N_NIMCALL(void, main_J6hEtTsWKO3x9aLBFH4OG8Q)(void);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tyRef_DiaJ5Sax3QVzuvIL0DQWDw)(void* p, NI op);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
N_CLOSURE(NimStringDesc*, readInputFile_ME40MBinydNzr8LBpNhJyg)(NimStringDesc* filename, void* ClE_0);
N_NIMCALL(NIM_BOOL, nosexistsFile)(NimStringDesc* filename);
N_NIMCALL(FILE*, open_hqzpWQbdA2B8l9a6wwNoP4g)(NimStringDesc* filename, tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ mode, NI bufSize);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
N_NIMCALL(NimStringDesc*, rawNewString)(NI cap);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, nimFrame)(TFrame* s);
N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(NIM_BOOL, readLine_sO1bQXVRA6RP9cdYJXNKeSw)(FILE* f, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(void, close_BWnr8V7RERYno9bIdPmw8Hw_2)(FILE* f);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_posixDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, nimmarkovDatInit000)(void);
extern TNimType NTI_13RNkKqUOX1TtorOUlKtqA_;
TNimType NTI_Cb3MXgX9cQud9cErDbZ8ADDg_;
extern TNimType NTI_Mpt8aZ13tT2AYV71yyfHcA_;
extern TNimType NTI_7BHnQsEj49a9c6QtudqWTo1w_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_DiaJ5Sax3QVzuvIL0DQWDw_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
STRING_LITERAL(TM_obis3mXdRVckmiGcrQBusA_3, "test_chain.txt", 14);
static N_NIMCALL(void, Marker_tyRef_DiaJ5Sax3QVzuvIL0DQWDw)(void* p, NI op) {
	tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg* a;
	a = (tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg*)p;
	nimGCvisit((void*)(*a).line2, op);
	nimGCvisit((void*)(*a).res4, op);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(138, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(216, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(276, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(378, "system.nim");
		nimln_(276, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(277, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(278, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(279, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(378, "system.nim");
		nimln_(279, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(280, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(281, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(282, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(283, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_CLOSURE(NimStringDesc*, readInputFile_ME40MBinydNzr8LBpNhJyg)(NimStringDesc* filename, void* ClE_0) {
	NimStringDesc* result;
	tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg* colonenvP_;
	nimfr_("readInputFile", "nimmarkov.nim");
{	result = (NimStringDesc*)0;
	colonenvP_ = (tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg*) ClE_0;
	switch ((*colonenvP_).colonstate_) {
	case -1: goto BeforeRet_;
	case 0: goto STATE0;
	case 1: goto STATE1;
	}
	STATE0: ;
	nimln_(4, "nimmarkov.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = nosexistsFile(filename);
		if (!T3_) goto LA4_;
		nimln_(5, "nimmarkov.nim");
		(*colonenvP_).fd1 = open_hqzpWQbdA2B8l9a6wwNoP4g(filename, ((tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ) 0), ((NI) -1));
		{
			nimln_(6, "nimmarkov.nim");
			(*colonenvP_).colontmp3_ = (*colonenvP_).fd1;
			nimln_(3230, "system.nim");
			asgnRefNoCycle((void**) (&(*colonenvP_).res4), rawNewString(((NI) 80)));
			{
				nimln_(3231, "system.nim");
				while (1) {
					NIM_BOOL T9_;
					nimln_(3217, "system.nim");
					T9_ = (NIM_BOOL)0;
					T9_ = readLine_sO1bQXVRA6RP9cdYJXNKeSw((*colonenvP_).colontmp3_, (&(*colonenvP_).res4));
					if (!T9_) goto LA8;
					nimln_(3230, "system.nim");
					asgnRefNoCycle((void**) (&(*colonenvP_).line2), (*colonenvP_).res4);
					(*colonenvP_).colonstate_ = ((NI) 1);
					nimln_(7, "nimmarkov.nim");
					result = copyString((*colonenvP_).line2);
					goto BeforeRet_;
					STATE1: ;
				} LA8: ;
			}
		}
		nimln_(8, "nimmarkov.nim");
		close_BWnr8V7RERYno9bIdPmw8Hw_2((*colonenvP_).fd1);
	}
	LA4_: ;
	(*colonenvP_).colonstate_ = ((NI) -1);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_NIMCALL(void, main_J6hEtTsWKO3x9aLBFH4OG8Q)(void) {
	nimfr_("main", "nimmarkov.nim");
	{
		tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg* readInputFile;
		readInputFile = (tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg*)0;
		nimln_(11, "nimmarkov.nim");
		readInputFile = (tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg*) newObj((&NTI_DiaJ5Sax3QVzuvIL0DQWDw_), sizeof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg));
		(*readInputFile).Sup.m_type = (&NTI_Cb3MXgX9cQud9cErDbZ8ADDg_);
		while (1) {
			NimStringDesc* line;
			tyProc_BLbewmRpDWz0SDsl9a9ci4xw T3_;
			memset((void*)(&T3_), 0, sizeof(T3_));
			T3_.ClP_0 = readInputFile_ME40MBinydNzr8LBpNhJyg; T3_.ClE_0 = readInputFile;
			line = T3_.ClP_0(((NimStringDesc*) &TM_obis3mXdRVckmiGcrQBusA_3), T3_.ClE_0);
			if (((NI*) readInputFile)[1] < 0) break;
			nimln_(12, "nimmarkov.nim");
			printf("%s\012", line? (line)->data:"nil");
			fflush(stdout);
		}
	}
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_timesDatInit000();
	stdlib_posixDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	nimmarkovDatInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_timesInit000();
	stdlib_posixInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	nimfr_("nimmarkov", "nimmarkov.nim");
	nimln_(14, "nimmarkov.nim");
	main_J6hEtTsWKO3x9aLBFH4OG8Q();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimmarkovDatInit000)(void) {
static TNimNode* TM_obis3mXdRVckmiGcrQBusA_2[5];
static TNimNode TM_obis3mXdRVckmiGcrQBusA_0[6];
NTI_Cb3MXgX9cQud9cErDbZ8ADDg_.size = sizeof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg);
NTI_Cb3MXgX9cQud9cErDbZ8ADDg_.kind = 17;
NTI_Cb3MXgX9cQud9cErDbZ8ADDg_.base = (&NTI_13RNkKqUOX1TtorOUlKtqA_);
TM_obis3mXdRVckmiGcrQBusA_2[0] = &TM_obis3mXdRVckmiGcrQBusA_0[1];
TM_obis3mXdRVckmiGcrQBusA_0[1].kind = 1;
TM_obis3mXdRVckmiGcrQBusA_0[1].offset = offsetof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg, colonstate_);
TM_obis3mXdRVckmiGcrQBusA_0[1].typ = (&NTI_Mpt8aZ13tT2AYV71yyfHcA_);
TM_obis3mXdRVckmiGcrQBusA_0[1].name = ":state";
TM_obis3mXdRVckmiGcrQBusA_2[1] = &TM_obis3mXdRVckmiGcrQBusA_0[2];
TM_obis3mXdRVckmiGcrQBusA_0[2].kind = 1;
TM_obis3mXdRVckmiGcrQBusA_0[2].offset = offsetof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg, fd1);
TM_obis3mXdRVckmiGcrQBusA_0[2].typ = (&NTI_7BHnQsEj49a9c6QtudqWTo1w_);
TM_obis3mXdRVckmiGcrQBusA_0[2].name = "fd1";
TM_obis3mXdRVckmiGcrQBusA_2[2] = &TM_obis3mXdRVckmiGcrQBusA_0[3];
TM_obis3mXdRVckmiGcrQBusA_0[3].kind = 1;
TM_obis3mXdRVckmiGcrQBusA_0[3].offset = offsetof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg, line2);
TM_obis3mXdRVckmiGcrQBusA_0[3].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_obis3mXdRVckmiGcrQBusA_0[3].name = "line2";
TM_obis3mXdRVckmiGcrQBusA_2[3] = &TM_obis3mXdRVckmiGcrQBusA_0[4];
TM_obis3mXdRVckmiGcrQBusA_0[4].kind = 1;
TM_obis3mXdRVckmiGcrQBusA_0[4].offset = offsetof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg, colontmp3_);
TM_obis3mXdRVckmiGcrQBusA_0[4].typ = (&NTI_7BHnQsEj49a9c6QtudqWTo1w_);
TM_obis3mXdRVckmiGcrQBusA_0[4].name = ":tmp3";
TM_obis3mXdRVckmiGcrQBusA_2[4] = &TM_obis3mXdRVckmiGcrQBusA_0[5];
TM_obis3mXdRVckmiGcrQBusA_0[5].kind = 1;
TM_obis3mXdRVckmiGcrQBusA_0[5].offset = offsetof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg, res4);
TM_obis3mXdRVckmiGcrQBusA_0[5].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_obis3mXdRVckmiGcrQBusA_0[5].name = "res4";
TM_obis3mXdRVckmiGcrQBusA_0[0].len = 5; TM_obis3mXdRVckmiGcrQBusA_0[0].kind = 2; TM_obis3mXdRVckmiGcrQBusA_0[0].sons = &TM_obis3mXdRVckmiGcrQBusA_2[0];
NTI_Cb3MXgX9cQud9cErDbZ8ADDg_.node = &TM_obis3mXdRVckmiGcrQBusA_0[0];
NTI_DiaJ5Sax3QVzuvIL0DQWDw_.size = sizeof(tyObject_Env_nimmarkovdotnim__Cb3MXgX9cQud9cErDbZ8ADDg*);
NTI_DiaJ5Sax3QVzuvIL0DQWDw_.kind = 22;
NTI_DiaJ5Sax3QVzuvIL0DQWDw_.base = (&NTI_Cb3MXgX9cQud9cErDbZ8ADDg_);
NTI_DiaJ5Sax3QVzuvIL0DQWDw_.marker = Marker_tyRef_DiaJ5Sax3QVzuvIL0DQWDw;
}

